title: Adam Silén
author: Adam Silén
email: adam.silen@outlook.com
url: "adamsilen.se"
baseurl: ""
description: Adam fotar för allmän beskådan.
lang: sv-SE
encoding: utf-8
goat_counter: "adamsilen"

favicon: "/site_icon.png"

theme_config:
  appearance: "auto"
  back_home_text: "Hem"
  back_link_text: "&laquo; Tillbaka"
  date_format: "%Y-%m-%d"
  show_description: false
  lowecase_titles: false

permalink: /:slug.html/

include:
  - upload

defaults:
  - scope:
      path: ""
    values:
      custom_js:
        - theme-toggle

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

kramdown:
    smart_quotes: ["rsquo", "rsquo", "rdquo", "rdquo"]
    footnote_backlink: "↑ Tillbaka"
